version: 0.2

env:
  variables:
    stage: 'stg'
  parameter-store:
    config_yml: 'office-maker-tenants-config-stg'

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - add-apt-repository ppa:rmescandon/yq -y && apt update && apt install -y yq
      - echo ${config_yml} >> config.yml
      - npm i -g yarn
      - yarn
  pre_build:
    commands:
      - export STAGE_NAME="test-$(date +%s)"
      - export STACK_NAME="office-maker-accounts-${STAGE_NAME}"
      - npx sls deploy -s ${STAGE_NAME}
      - yarn post-deploy
  build:
    commands: |
      yarn test && yarn test-flow && \
      echo '*** Test succeeded ***'

      export BUILD_STATUS="$?"

      if [ ${BUILD_STATUS} = 0 && "$CODEBUILD_WEBHOOK_TRIGGER" = "branch/release" ]; then
        echo 'Deploying to staging environment......'
        ./node_modules/.bin/sls deploy -s ${stage} && yarn post-deploy
      fi
  post_build:
    commands:
      - npx sls remove -s ${STAGE_NAME} && exit ${BUILD_STATUS}

cache:
  paths:
    - '~/.npm/**/*'
