version: 0.2

env:
  variables:
    stage: 'stg'
  parameter-store:
    config_yml: 'office-maker-tenants-config-template'

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - add-apt-repository ppa:rmescandon/yq -y && apt update && apt install -y yq
      - export STAGE_NAME="test$(date +%s)"
      - echo "${config_yml}" | sed "s/<stage>/${STAGE_NAME}/g" > config.yaml
      - npm i -g yarn
      - yarn --frozen-lockfile
  build:
    commands: |
      npx sls deploy -s ${STAGE_NAME} && yarn post-deploy
      yarn test && \
      echo '*** Test succeeded ***'
      export BUILD_STATUS="$?"
      if [ ${BUILD_STATUS} = 0 && "$CODEBUILD_WEBHOOK_TRIGGER" = "branch/release" ]; then
        echo "${config_yml}" | sed "s/<stage>/${stage}/g" > config.yaml
        echo 'Deploying to staging environment......'
        ./node_modules/.bin/sls deploy -s ${stage} && yarn post-deploy
      fi
  post_build:
    commands:
      - yarn pre-remove
      - npx sls remove -s ${STAGE_NAME} && exit ${BUILD_STATUS}

cache:
  paths:
    - '~/.npm/**/*'
