# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: Office-Maker-Account

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-tag-api-gateway
  - serverless-tag-cloud-watch-logs
  - serverless-plugin-warmup

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  memorySize: 128
  timeout: 15
  stackTags:
    Name: ${self:service}-${self:provider.stage}
  tags:
    <<: &commonTags
      Production: ${self:service}
      Environment: ${self:provider.stage}
  environment:
    DB_TENANT_NAME: !Ref TenantInfoDynamoDB
    DB_USER_PRI_NAME: !Ref UserPrivilegeDynamoDB
    ADMIN_POOL_ID: !Ref CognitoUserPoolForTenant
    ADMIN_CLIENT_ID: !Ref CognitoUserPoolClientForTenant
    USER_POOL_ID: !Ref CognitoUserPoolForUsers
    BASE_URL: ${file(config:yaml):API_BASE_URL}

custom:
  app: worksmap
  apiGatewayTags: *commonTags
  cloudWatchLogsTags: *commonTags
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    packagerOptions: {}
    includeModules: true
  publicKey: ${file(./config.yaml):SSM.PUBLIC_KEY}
  privateKey: ${file(./configy.yaml):SSM.PRIVATE_KEY}

package:
  individually: true

# The `functions` block defines what code to deploy
functions:
  registerTenant:
    warmup: prod
    handler: src/admin/registerTenant.handler
    name: ${self:service}-${self:provider.stage}-createTenant
    role: !GetAtt APICreateTenantLambdaRole.Arn
    events: # POST tenants/tenant=<tenant>
      - http:
          path: admin/tenants
          method: post
          <<: &cognitoAdminAuthorizer
            authorizer:
              type: COGNITO_USER_POOLS
              authorizerId: !Ref APIGatewayAuthorizerForTenant

  deleteTenant:
    warmup: prod
    handler: src/admin/deleteTenant.handler
    name: ${self:service}-${self:provider.stage}-deleteTenant
    events: # DELETE tenants/{tenant_name}
      - http:
          path: admin/tenants/{tenant_name}
          method: delete
          <<: *cognitoAdminAuthorizer
    role: !GetAtt APICRUDTenantDBLambdaRole.Arn
    environment:
      TENANT_SAML_NAME_PREFIX: ${self:custom.app}

  checkTenant:
    warmup: prod
    handler: src/admin/checkTenant.handler
    name: ${self:service}-${self:provider.stage}-checkTenant
    events: # HEAD tenants/{tenant_name}
      - http:
          path: admin/tenants/{tenant_name}
          method: head
          <<: *cognitoAdminAuthorizer
    role: !GetAtt APICRUDTenantDBLambdaRole.Arn

  setTenantDetail:
    warmup: prod
    handler: src/admin/setTenantDetailInfo.handler
    name:
    events:
      # body{
      #      jwtExpireTime?: string | undefined
      #      stateExpireTime?: string | undefined
      #      redirectUrl?: string | undefined
      # }   if undefined, will use default value   json
      - http:
          path: admin/tenants/{tenant}/info
          method: post
          <<: *cognitoAdminAuthorizer
    role: !GetAtt APICRUDTenantDBLambdaRole.Arn
    environment:
      WWW_TEMPLATE_URL: ${file(config:yaml):WWW_TEMPLATE_URL}

  getClientInfo:
    warmup: prod
    handler: src/admin/getClientInfo.handler
    name: ${self:service}-{self:provider.stage}-getClientInfo
    events:
      - http:
          path: admin/client-info
          method: get
          <<: *cognitoAdminAuthorizer
    role: !GetAtt APILambdaBasicRole.Arn

  registerSAMLProvider:
    warmup: prod
    handler: src/admin/SAMLProviderRegister.handler
    name: ${self:service}-${self:provider.stage}-addSAMLProvider
    events: # POST saml-providers/tenant=<tenant> body {metadata | metadataUrl }
      - http:
          path: admin/providers/
          method: post
          <<: *cognitoAdminAuthorizer
    role: !GetAtt APICRUDSAMLProviderLambdaRole.Arn
    environment:
      TENANT_SAML_NAME_PREFIX: ${self:custom.app}

  updateSAMLProvider:
    warmup: prod
    handler: src/admin/SAMLProviderUpdate.handler
    name: ${self:service}-${self:provider.stage}-updateSAMLProvider
    events: # POST admin/providers/{tenant} body: {metadata | metadataUrl}
      - http:
          path: admin/providers/{tenant}
          method: post
          <<: *cognitoAdminAuthorizer
    role: !GetAtt APICRUDSAMLProviderLambdaRole.Arn
    environment:
      TENANT_SAML_NAME_PREFIX: ${self:custom.app}

  deleteSAMLProvider:
    warmup: prod
    handler: src/admin/SAMLProviderDelete.handler
    name: ${self:service}-${self:provider.stage}-deleteSAMLProvider
    events: # delete admin/providers/{tenant}
      - http:
          path: admin/providers/{tenant}
          method: delete
          <<: *cognitoAdminAuthorizer
    role: !GetAtt APICRUDSAMLProviderLambdaRole.Arn
    environment:
      TENANT_SAML_NAME_PREFIX: ${self:custom.app}

  getSAMLProvider:
    warmup: prod
    handler: src/admin/SAMLProviderGet.handler
    name: ${self:service}-${self:provider.stage}-getSAMLProvider
    events: # get admin/providers/{tenant}
      - http:
          path: admin/providers/{tenant}
          method: get
          <<: *cognitoAdminAuthorizer
    role: !GetAtt APICRUDSAMLProviderLambdaRole.Arn
    environment:
      TENANT_SAML_NAME_PREFIX: ${self:custom.app}

  redirectToLoginUrl:
    warmup: prod
    handler: src/user/generateLoginUrl.handler
    name: ${self:service}-${self:provider.stage}-generateLoginUrl
    events: # get login/url?tenant=<tenant>
      - http:
          path: saml/login/
          method: get
    role: !GetAtt APIUserLambdaRole.Arn
    environment:
      COGNITO_DOMAIN: ${file(config.yaml):COGNITO.USERS_USER_POOL_COGNITO_DOMAIN}
      COGNITO_REGION: ${self:provider.region}
      TENANT_SAML_NAME_PREFIX: ${self:custom.app}
      COGNITO_USER_CLIENT_ID: !Ref CognitoUserPoolClientForUser
      privateKey: ${self:custom.privateKey}

  userLoginCallback:
    warmup: prod
    handler: src/user/loginHandler.handler
    name: ${self:service}-${self:provider.stage}-loginHandler
    events:
      - http:
          path: saml/login/callback
          method: get
    role: !GetAtt APIUserLambdaRole.Arn
    environment:
      publicKey: ${self:custom.publicKey}
      privateKey: ${self:custom.privateKey}
      COGNITO_DOMAIN: ${file(config.yaml):COGNITO.USERS_USER_POOL_COGNITO_DOMAIN}
      COGNITO_REGION: ${self:provider.region}
      COGNITO_USER_CLIENT_ID: !Ref CognitoUserPoolClientForUser

resources:
  Resources: ${file(cloudformation/cf_for_serverless.yaml):Resources}
  Outputs: ${file(cloudformation/cf_for_serverless.yaml):Outputs}
